"""What Linux and macOS genuinely share. Imported only by `_os/linux/` and `_os/macos/`."""
from __future__ import annotations

import os
import signal
import stat
import subprocess
from pathlib import Path


def spawn_options() -> dict:
    """Start each command in its own session, so the command and its children form one group."""
    return {"start_new_session": True}


def stdin_is_interactive() -> bool:
    """True when stdin is a terminal (a person can answer)."""
    try:
        return os.isatty(0)
    except (OSError, ValueError):
        return False


def kill_tree(proc: subprocess.Popen) -> None:
    """End proc's whole process group (see `spawn_options`). Never raises."""
    if proc.poll() is not None:
        return
    try:
        os.killpg(proc.pid, signal.SIGKILL)
    except (OSError, AttributeError):  # already gone, or no killpg on this platform
        pass
    try:
        proc.kill()
    except OSError:
        pass


# --- launchers -------------------------------------------------------------------------
LAUNCHER_SUFFIX = ".sh"


def _sh(value) -> str:
    """A POSIX single-quoted literal."""
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def launcher_text(repo_root: Path, script: str, args: list[str]) -> str:
    """Run `script` (relative to repo_root) with fixed args plus any passed through.
    Prefers the repository's .venv interpreter, falls back to `uv run`."""
    fixed = " ".join(_sh(arg) for arg in args)
    return f"""#!/usr/bin/env sh
# Generated by gitSpecOps. Do not edit by hand; regenerate it instead.
set -eu
cd {_sh(repo_root)}
if [ -x ".venv/bin/python" ]; then
    exec .venv/bin/python {_sh(script)} {fixed} "$@"
else
    exec uv run python {_sh(script)} {fixed} "$@"
fi
"""


def write_launcher(directory: Path, base: str, repo_root: Path, script: str,
                   args: list[str]) -> Path:
    """Write an executable `<base>.sh` into directory and return it."""
    path = Path(directory) / f"{base}{LAUNCHER_SUFFIX}"
    path.write_text(launcher_text(repo_root, script, args), encoding="utf-8", newline="\n")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def launcher_files(directory: Path, base: str) -> list[Path]:
    return [Path(directory) / f"{base}{LAUNCHER_SUFFIX}"]


# --- scheduled runs ----------------------------------------------------------------------
# Not implemented yet on Linux or macOS. Rather than inventing a cron line or a systemd timer the
# user did not ask for, say so and point at the launcher, which cron or a timer can run as-is.
def _schedule_unsupported(command: Path | None = None) -> int:
    print("Scheduled refresh is implemented for Windows Task Scheduler only.")
    if command is not None:
        print(f"Run this from cron or a systemd --user timer instead: {command}")
    return 2


def install_monthly(task_name: str, command: Path, day: int, time_of_day: str) -> int:
    return _schedule_unsupported(command)


def status(task_name: str) -> int:
    return _schedule_unsupported()


def remove(task_name: str) -> int:
    return _schedule_unsupported()
