"""Windows: a generated launcher is a PowerShell script plus a double-clickable .bat shim.

The .ps1 holds the logic; the .bat exists because Explorer will not run a .ps1 on double-click
and because Task Scheduler runs a .bat directly. When double-clicked, the shim keeps its window
open so the output can be read; run from a console or a scheduler it just returns the exit code.
"""
from __future__ import annotations

from pathlib import Path

SUFFIX = ".bat"


def _ps(value) -> str:
    """A PowerShell single-quoted literal."""
    return "'" + str(value).replace("'", "''") + "'"


def launcher_text(repo_root: Path, script: str, args: list[str]) -> str:
    """The .ps1: run `script` (relative to repo_root) with fixed args plus any passed through.
    Prefers the repository's .venv interpreter, falls back to `uv run`."""
    fixed = ", ".join(_ps(arg) for arg in args)
    return f"""# Generated by gitSpecOps. Do not edit by hand; regenerate it instead.
$ErrorActionPreference = "Stop"
$RepoRoot = {_ps(repo_root)}
$VenvPy = Join-Path $RepoRoot '.venv\\Scripts\\python.exe'
$Fixed = @({fixed})
Push-Location $RepoRoot
try {{
    if (Test-Path $VenvPy) {{
        & $VenvPy {_ps(script)} @Fixed @args
    }} else {{
        uv run python {_ps(script)} @Fixed @args
    }}
}} finally {{ Pop-Location }}
exit $LASTEXITCODE
"""


def _shim_text(ps1_name: str) -> str:
    return f"""@echo off
setlocal
rem Shim: the real logic lives in {ps1_name}. This keeps double-click and Task Scheduler working.
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0{ps1_name}" %*
set "RC=%ERRORLEVEL%"
rem When double-clicked from Explorer, %cmdcmdline% contains this script's name and the
rem console would normally close on exit. Keep it open (no keypress) so the output can be
rem inspected. When run from an existing console or another process, just propagate the code.
echo "%cmdcmdline%" | find /i "%~nx0" >nul 2>&1 && (
    echo.
    echo Finished with exit code %RC%. Window left open for inspection; close it when done.
    cmd /k
)
exit /b %RC%
"""


def write_launcher(directory: Path, base: str, repo_root: Path, script: str,
                   args: list[str]) -> Path:
    """Write `<base>.ps1` and `<base>.bat` into directory. Returns the .bat (what to run)."""
    directory = Path(directory)
    ps1 = directory / f"{base}.ps1"
    bat = directory / f"{base}{SUFFIX}"
    ps1.write_text(launcher_text(repo_root, script, args), encoding="utf-8", newline="\r\n")
    bat.write_text(_shim_text(ps1.name), encoding="utf-8", newline="\r\n")
    return bat


def launcher_files(directory: Path, base: str) -> list[Path]:
    """Every file `write_launcher` would create for this base name."""
    return [Path(directory) / f"{base}.ps1", Path(directory) / f"{base}{SUFFIX}"]
